### ISSUE TITLE
[Bug] The logic from GaloisElement to Galois Index.

### ISSUE THREAD

**Issue by fionser** [encryptorion-lab/phantom-fhe#1]
It seems current Phantom determines the index of the GaloisKey to used bascially from "order of the given galois elements" 
within the `create_galois_key()`. However, the PhantomContext creates the GaloisTool **before** the GaloisKeys are generated (using some fixed order of galois elements).

**Comment by fionser** [comment]
I see, we can set the galois_elts in EncryptionParamers orz....

**Comment by D4rkCrypto** [comment]
Thanks for highlighting this. We plan to enhance our documentation shortly.
