### ISSUE TITLE
test failed in ckks module

### ISSUE THREAD

**Issue by black6816** [encryptorion-lab/phantom-fhe#13]
hi, i test example_context , when choose 3 (ckks), i get std::logic_error

Example: CKKS cipher multiply plain vector
Number of slots: 32768
------------- Symmetric case ---------------
Message vector: 

    [ 0.9227586 + i * 0.2618946, 0.1267837 + i * 0.5705178, 0.8383549 + i * 0.7144885, ..., 0.5804810 + i * 0.4796554, 0.4804327 + i * 0.6007516, 0.0128479 + i * 0.0408400 ]

Constant vector: 

    [ 0.9111793 + i * 0.3698805, 0.9890116 + i * 0.5103588, 0.5184918 + i * 0.9594647, ..., 0.9026671 + i * 0.5765395, 0.9409581 + i * 0.6455890, 0.2562707 + i * 0.7707110 ]

Result vector: 

    [ 0.7439288 + i * 0.5799434, -0.1657783 + i * 0.6289539, -0.2508463 + i * 1.1748284, ..., 0.2474408 + i * 0.7676394, 0.0642283 + i * 0.8754442, -0.0281833 + i * 0.0203681 ]

------------- Asymmetric case ---------------
Message vector: 

    [ 0.9815584 + i * 0.2731341, 0.5796478 + i * 0.8939902, 0.9127351 + i * 0.8963753, ..., 0.2358352 + i * 0.5530513, 0.7679002 + i * 0.5050227, 0.8801482 + i * 0.6353645 ]

Constant vector: 

    [ 0.0000000 + i * 0.0000000, 0.0000000 + i * 0.0000000, 0.5894318 + i * 0.9943603, ..., 0.0000000 + i * 0.0000000, 0.0000000 + i * 0.0000000, 0.0000000 + i * 0.0000000 ]

Result vector: 

    [ -0.0000000 + i * -0.0000000, -0.0000000 + i * 0.0000000, -0.3533249 + i * 1.4359396, ..., -0.0000000 + i * -0.0000000, -0.0000000 + i * -0.0000000, 0.0000000 + i * 0.0000000 ]

Example: CKKS HomMul test
Number of slots: 32768
Message vector: 

    [ 0.7402569 + i * 0.4013663, 0.5244954 + i * 0.0358114, 0.2628577 + i * 0.0019818, ..., 0.1825986 + i * 0.7990596, 0.2590451 + i * 0.8472831, 0.4585961 + i * 0.5650429 ]

Message vector: 

    [ 0.1756010 + i * 0.5514546, 0.0161853 + i * 0.5452628, 0.6544692 + i * 0.1025220, ..., 0.3331721 + i * 0.6364909, 0.3577494 + i * 0.6106590, 0.1390900 + i * 0.2366128 ]

Compute x*y*x.
    + Scale of x*y after rescale: 50 bits
    + Scale of x: 50 bits
Result vector: 

    [ -0.2597525 + i * 0.3176968, -0.0160515 + i * 0.1499081, 0.0451106 + i * 0.0077651, ..., -0.3873576 + i * -0.2879507, -0.5008782 + i * -0.2403663, -0.1377810 + i * 0.0463018 ]

Example: CKKS HomRot test
Number of slots: 32768
Message vector: 

    [ 0.7197661 + i * 0.4617180, 0.9465300 + i * 0.4766647, 0.8920013 + i * 0.6175773, ..., 0.1734723 + i * 0.5709555, 0.7073019 + i * 0.7106265, 0.8394506 + i * 0.5103716 ]

Compute, rot vector x.
Result vector: 

    [ 0.0619175 + i * 0.7028560, 0.2658539 + i * 0.1903272, 0.8962101 + i * 0.3158847, ..., 0.7197661 + i * 0.4617180, 0.9465300 + i * 0.4766647, 0.8920013 + i * 0.6175773 ]

Example: CKKS HomConj test
Message vector: 

    [ 0.1376041 + i * 0.1365336, 0.6372852 + i * 0.5182673, 0.7060895 + i * 0.8380807, ..., 0.8702146 + i * 0.9134485, 0.5028721 + i * 0.2934525, 0.5629598 + i * 0.4517105 ]

Compute, conjugate vector x.
Result vector: 

    [ 0.1376041 + i * -0.1365336, 0.6372852 + i * -0.5182673, 0.7060894 + i * -0.8380807, ..., 0.8702146 + i * -0.9134485, 0.5028721 + i * -0.2934525, 0.5629598 + i * -0.4517105 ]

terminate called after throwing an instance of 'std::logic_error'
  what():  error in example_ckks_small_param
Aborted (core dumped)

**Comment by D4rkCrypto** [comment]
Thank you for reporting this issue. Could you please provide more details about your hardware and software environment? This will help us better understand the problem and work towards a solution.

**Comment by black6816** [comment]
my env  RTX 3090， ubutun20.04 CUDA11.7

**Comment by D4rkCrypto** [comment]
We are aware of some reported issues with CUDA 11.x. We will attempt to reproduce the bug in your environment. In the meantime, you might want to consider upgrading to CUDA 12.x or the latest version, as our extensive testing in those environments has not revealed any issues.

**Comment by black6816** [comment]
the bfv/bgv test is ok, it is a strange error

**Comment by grueyg** [comment]
```shell
terminate called after throwing an instance of 'std::logic_error'
what(): error in example_ckks_small_param
Aborted (core dumped)
```

The same error exists on CUDA11.6

**Comment by D4rkCrypto** [comment]
There are some compatibility issues when using CUDA 11, and I’m still unsure of the exact location of the bug in the code. The quickest solution would be to upgrade CUDA to the latest version, but I will also attempt to fix the issue once I’ve completed other high-priority tasks.
