### ISSUE TITLE
Support for CPU version of encode, decode and enceypt, decrypt function

### ISSUE THREAD

**Issue by JerryFishY** [encryptorion-lab/phantom-fhe#16]
Thanks for this project! I am wondering if there are CPU APIs for encoding, decoding and encryption, decryption. As in many real-world applications like private CNN inference, the client who only owns a CPU needs to encrypt the plaintexts,  and sends them to the server. The server is then able to perform HE computations on GPUs. And many other libraries have CPU APIs.

**Comment by D4rkCrypto** [comment]
We don’t have CPU APIs at the moment, but we plan to develop a standalone client-side library soon. It will be optimized for embedded systems and fully compatible with the current GPU library.
