### ISSUE TITLE
How to change special modulus

### ISSUE THREAD

**Issue by hpc-cool** [encryptorion-lab/phantom-fhe#17]
I would like to reproduce the experimental results in your paper. May I ask how special modulus, which is P in the parameter |PQ| of Table VI, VII and VIII in the paper, is changed to the value in the paper in code? Can you give an example。

**Comment by sher1e** [comment]
Thank you for your question. Let me explain how to determine the parameters:

First, determine |QP| based on 128-bit security requirements.

For BGV and CKKS schemes:
Calculate |P_i| as approximately (|QP| - |P|)/k. Set |Q_0| approximately equal to |P_i|, then distribute remaining |Q_i| values roughly equally. For example, with parameters (|N|, |Q|, |QP|, L, k) = (13, 180, 218, 4, 1), set |P| = 38 and distribute |Q| = 180 as: 38 + 36 + 36 + 35 + 35.

For BFV scheme:
Set |P_i| = 60, and calculate each |Q_i| as approximately (|QP| - |P|)/(L + 1). For example, with parameters (|N|, |Q|, |QP|, L, k) = (13, 140, 200, 2, 1), set |P| = 60 and distribute |Q| = 140 as: 48 + 46 + 46.

Minor variations in |Q_i| values won't significantly affect performance. For instance, both distributions (48, 46) and (47, 47) for (|Q_1|, |Q_2|) are acceptable.

I hope this helps! Let me know if you need any clarification.

Best regards

**Comment by sher1e** [comment]
Thank you for your question. Let me explain how to determine the parameters:

First, determine $|QP|$ based on 128-bit security requirements.

For BGV and BFV schemes:
Calculate $|p_i|$ as approximately $(|QP| - |P|)/k$, then distribute remaining $|q_i|$ values roughly equally.

For CKKS scheme:
Set $|p_i| = 60$, and $|q_0|$ approximately equal to $|p_i|$, and set each remaining $|q_i| = 40$. 

Minor variations in $|q_i|$ values won't significantly affect performance.

For more detailed examples, please refer to the benchmark files:
- benchmark/bgv_bench.cu
- benchmark/bfv_bench.cu
- benchmark/ckks_bench.cu

I hope this helps! Let me know if you need any clarification.

Best regards
