### ISSUE TITLE
Can nvidia RTX series support this library?

### ISSUE THREAD

**Issue by JINGBO314** [encryptorion-lab/phantom-fhe#2]
Can nvidia RTX series support this library?

**Comment by D4rkCrypto** [comment]
Yes, PhantomFHE has been tested and verified on RTX 30 and 40 series.

**Comment by JINGBO314** [comment]
Thank you very much for your reply. Why is the GPU utilization so low when I use an RTX30 series GPU?

**Comment by D4rkCrypto** [comment]
Probably caused by small parameters, also HE operations cannot fully occupy GPU. You can try large parameters like $n = 2^16$ and the corresponding longest modulus chain, to see if the GPU utilization is still low.

**Comment by JINGBO314** [comment]
Ok, thanks for your reply, I'll try it
