### ISSUE TITLE
Performance Comparisons with Microsoft SEAL

### ISSUE THREAD

**Issue by ttttonyhe** [encryptorion-lab/phantom-fhe#3]
Hi,

After doing some preliminary testing, I found that Phantom FHE, despite utilizing GPU acceleration, did not result in better performance than Microsoft SEAL when running the same program with the same parameters on the same machine (4*NVIDIA A100). Though my test was not very extensive, and the test program only consists of simple operations like additions and multiplications. I was wondering if anyone did more performance comparisons between the two libraries and could show me the results you got.

Thank you!

**Comment by D4rkCrypto** [comment]
There are several possible reasons why PhantomFHE doesn't outperform SEAL in your test:
- Crypto parameters are small (e.g. dimension is 4096). In this case, GPU cannot achieve its peak performance.
- The demo program is rather simple (e.g. one addition/multiplication). In this case, if you benchmark the whole program including the preprocessing phase (crypto context initialization, key generation, etc.), it may perform worse than CPU-only library. The main reason is that preprocessing in PhantomFHE also computes on CPU and then copy to GPU. I suggest benchmark the online phase only (cipher text operations).

BTW, PhantomFHE currently doesn't support multi-GPUs, it runs on only GPU 0 by default.

I suggest taking a look at benchmarking results in our paper (also on A100), to see if your card can reproduce similar results.

Thanks for your issue!

**Comment by ttttonyhe** [comment]
Thank you for your reply! 

Good to know:
> BTW, PhantomFHE currently doesn't support multi-GPUs, it runs on only GPU 0 by default.

Will definitely do:
> I suggest taking a look at benchmarking results in our paper (also on A100), to see if your card can reproduce similar results.
